import { join } from "node:path";
import type { ProjectData } from "../domain/types.ts";
import { serializeProject } from "../domain/store.ts";

export interface SnapshotBackendInfo {
  kind: "git" | "file";
  available: boolean;
  reason?: string;
}

/**
 * Optional hidden Git backend.  It accepts high-level operations only and
 * never accepts a user-provided shell command or argument vector.  File
 * snapshots remain the default and work without Git or process permissions.
 */
export class GitSnapshotAdapter {
  readonly info: SnapshotBackendInfo = { kind: "git", available: false };

  constructor(readonly projectRoot: string) {}

  private async run(
    args: readonly string[],
  ): Promise<{ code: number; stdout: string; stderr: string }> {
    try {
      const command = new Deno.Command("git", {
        args: [...args],
        cwd: this.projectRoot,
        stdout: "piped",
        stderr: "piped",
      });
      const output = await command.output();
      return {
        code: output.code,
        stdout: new TextDecoder().decode(output.stdout),
        stderr: new TextDecoder().decode(output.stderr),
      };
    } catch (caught) {
      return { code: 127, stdout: "", stderr: String(caught) };
    }
  }

  async detect(): Promise<SnapshotBackendInfo> {
    const result = await this.run(["rev-parse", "--is-inside-work-tree"]);
    if (result.code === 0 && result.stdout.trim() === "true") {
      this.info.available = true;
      delete this.info.reason;
    } else {
      this.info.available = false;
      this.info.reason = "项目目录不是 Git 工作区，继续使用文件快照";
    }
    return { ...this.info };
  }

  async create(
    data: ProjectData,
    name: string,
    note = "",
  ): Promise<string | null> {
    const info = await this.detect();
    if (!info.available) return null;
    // The canonical file is staged through a fixed high-level path.  No raw
    // Git parameters are exposed to callers.
    await Deno.writeTextFile(
      join(this.projectRoot, "project.json"),
      serializeProject(data),
    );
    const add = await this.run(["add", "--", "project.json"]);
    if (add.code !== 0) throw new Error(`历史版本保存失败: ${add.stderr}`);
    const message = `AI Course Workbench: ${name}${note ? ` — ${note}` : ""}`
      .slice(0, 200);
    const commit = await this.run(["commit", "--quiet", "-m", message]);
    if (commit.code !== 0) {
      throw new Error(`历史版本保存失败: ${commit.stderr}`);
    }
    const hash = await this.run(["rev-parse", "HEAD"]);
    return hash.code === 0 ? hash.stdout.trim() : null;
  }

  async diff(firstCommit: string, secondCommit: string): Promise<string> {
    // Commit ids are generated by Git and are validated before interpolation
    // into the fixed argument list.
    if (
      !/^[0-9a-f]{7,64}$/i.test(firstCommit) ||
      !/^[0-9a-f]{7,64}$/i.test(secondCommit)
    ) {
      throw new Error("历史版本编号无效");
    }
    const result = await this.run([
      "diff",
      "--no-ext-diff",
      "--unified=0",
      firstCommit,
      secondCommit,
      "--",
      "project.json",
    ]);
    if (result.code !== 0) {
      throw new Error(`历史版本差异读取失败: ${result.stderr}`);
    }
    return result.stdout;
  }

  async restore(commit: string): Promise<void> {
    if (!/^[0-9a-f]{7,64}$/i.test(commit)) throw new Error("历史版本编号无效");
    const result = await this.run([
      "restore",
      "--source",
      commit,
      "--",
      "project.json",
    ]);
    if (result.code !== 0) {
      throw new Error(`历史版本恢复失败: ${result.stderr}`);
    }
  }

  /** Exposes the backend choice without exposing commit/branch terminology to UI. */
  backendId(): string {
    return this.info.available ? "git" : "file";
  }
}

export class FileSnapshotAdapter {
  readonly info: SnapshotBackendInfo = {
    kind: "file",
    available: true,
    reason: "开放项目文件快照，不依赖 Git",
  };
}
