import {
  appendBlock,
  BrowserSessionStore,
  createDocument,
  createEmptyProjectData,
  DesktopService,
  MemorySecretStore,
  type ProjectData,
  initializeContentStatuses,
} from "../src/domain/index.ts";

function assert(condition: unknown, message: string): asserts condition {
  if (!condition) throw new Error(message);
}

let pageCounter = 0;

function response(value: unknown, status = 200): Response {
  return new Response(JSON.stringify(value), {
    status,
    headers: { "content-type": "application/json" },
  });
}

function projectWithLesson(title = "浏览器刷新测试"): ProjectData {
  const project = createEmptyProjectData(title);
  const stage = project.stages[0];
  const contentId = crypto.randomUUID();
  const document = createDocument(project, contentId);
  project.content_items.push({
    id: contentId,
    project_id: project.project.id,
    stage_id: stage?.id ?? null,
    code: "S01-01",
    title: "刷新后继续的课程",
    type: "lesson",
    description: "",
    order_index: 0,
    document_id: document.id,
    archived: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  });
  initializeContentStatuses(project, contentId);
  appendBlock(project, contentId, "paragraph", "刷新前的正文");
  return project;
}

async function createDesktopProject(): Promise<{
  directory: string;
  desktop: DesktopService;
  project: ProjectData;
}> {
  const directory = await Deno.makeTempDir({ prefix: "acw-browser-session-" });
  const secrets = new MemorySecretStore();
  const desktop = new DesktopService(
    directory,
    { app_instance_id: `browser-session-${crypto.randomUUID()}` },
    secrets,
    { credential_store: secrets },
  );
  await desktop.open();
  const project = projectWithLesson();
  const created = await desktop.commands.execute("project.create", {
    title: project.project.title,
  });
  assert(!created.error, "test project should be created");
  // Keep the id generated by the service so the browser service and session
  // envelope exercise one real canonical identity.
  project.project.id = (created.value as ProjectData).project.id;
  // The generated fixture starts with its own identity; update every
  // project-scoped row before handing it to the real validator.
  for (const rows of Object.values(project)) {
    if (!Array.isArray(rows)) continue;
    for (const row of rows) {
      if (row && typeof row === "object" && "project_id" in row) {
        (row as { project_id: string }).project_id = project.project.id;
      }
    }
  }
  const saved = await desktop.commands.execute("project.save", { project });
  assert(!saved.error, "test project should be saved");
  return { directory, desktop, project };
}

function browserFetch(desktop: DesktopService): typeof fetch {
  return async (input, init = {}) => {
    const url = new URL(String(input), "http://browser.test");
    if (url.pathname === "/api/session") {
      if ((init.method || "GET").toUpperCase() === "GET") {
        return response({ value: await desktop.loadBrowserSession() });
      }
      const body = JSON.parse(String(init.body || "{}")) as { session?: unknown };
      try {
        await desktop.saveBrowserSession(body.session);
        return response({ value: null });
      } catch (caught) {
        const error = caught && typeof caught === "object" && "error" in caught
          ? (caught as { error: unknown }).error
          : { code: "browser_session_unavailable", user_message: "阅读位置暂时不可用" };
        return response({ error }, 400);
      }
    }
    if (url.pathname === "/api/command") {
      const body = JSON.parse(String(init.body || "{}")) as {
        name?: string;
        input?: unknown;
      };
      const execution = await desktop.commands.execute(
        body.name as never,
        body.input ?? {},
      );
      return execution.error
        ? response({ error: execution.error }, 400)
        : response({ value: execution.value });
    }
    if (url.pathname === "/api/query") {
      const body = JSON.parse(String(init.body || "{}")) as {
        name?: string;
        input?: unknown;
      };
      try {
        return response({
          value: await desktop.queries.execute(body.name as never, body.input ?? {}),
        });
      } catch (caught) {
        return response({ error: { user_message: String(caught) } }, 400);
      }
    }
    return response({ error: { user_message: "not found" } }, 404);
  };
}

/** Boot one page with a fresh bridge and fresh WorkbenchStore instance. */
async function bootBrowserPage(desktop: DesktopService): Promise<any> {
  const runtime = globalThis as typeof globalThis & {
    document?: unknown;
    __TAURI__?: unknown;
    __workbench?: unknown;
    __workbenchReady?: Promise<unknown>;
  };
  const root = {
    innerHTML: "",
    querySelector: (selector: string) => selector === "#app" ? root : null,
    querySelectorAll: () => [],
    classList: { add: () => {}, remove: () => {}, toggle: () => {} },
  };
  runtime.document = {
    querySelector: (selector: string) => selector === "#app" ? root : null,
    querySelectorAll: () => [],
    addEventListener: () => undefined,
  };
  runtime.__TAURI__ = undefined;
  globalThis.fetch = browserFetch(desktop);
  pageCounter += 1;
  await import(`../app/main.js?browser-page-${pageCounter}`);
  await runtime.__workbenchReady;
  return runtime.__workbench;
}

Deno.test("browser page reload restores reader position, then saves canonical edits before the next reload", async () => {
  const previousDocument = (globalThis as typeof globalThis & { document?: unknown }).document;
  const previousTauri = (globalThis as typeof globalThis & { __TAURI__?: unknown }).__TAURI__;
  const previousFetch = globalThis.fetch;
  const { desktop, directory, project } = await createDesktopProject();
  try {
    const first = await bootBrowserPage(desktop);
    first.enterProject();
    const lesson = project.content_items[0];
    assert(lesson, "fixture must contain a lesson");
    first.openItem(lesson.id);
    first.ui.route = "media";
    first.ui.mode = "preview";
    first.ui.rightPanel = "status";
    first.ui.leftCollapsed = true;
    await first.persistSession(first.session());

    const canonicalBeforeRefresh = await Deno.readTextFile(`${directory}/project.json`);
    assert(!canonicalBeforeRefresh.includes("left_collapsed"), "reader state must not enter canonical content");

    // A full page reload creates a new DesktopBridge; only the service sidecar
    // survives, so this is not an in-process memory-session test.
    const second = await bootBrowserPage(desktop);
    assert(second.ui.screen === "project", "refresh must reopen the project shell instead of the launcher");
    assert(second.data.project.id === project.project.id, "refresh must reopen the same canonical project");
    assert(second.ui.activeId === lesson.id, "refresh must restore the active lesson");
    assert(second.ui.route === "media", "refresh must restore the current view");
    assert(second.ui.mode === "preview", "refresh must restore the reading mode");
    assert(second.ui.rightPanel === "status", "refresh must restore the right panel");
    assert(second.ui.leftCollapsed === true, "refresh must restore panel collapse state");

    const block = second.data.blocks.find((candidate: any) => candidate.document_id === lesson.document_id);
    assert(block, "fixture must contain a lesson block");
    second.commit("刷新后编辑", (data: ProjectData) => {
      const target = data.blocks.find((candidate) => candidate.id === block.id);
      assert(target, "edit target must still exist");
      target.content = "刷新后保存的正文";
    });
    assert(await second.flush(), "edit must save through the service bridge");

    const third = await bootBrowserPage(desktop);
    assert(third.ui.screen === "project", "second refresh must keep the project shell open");
    const savedBlock = third.data.blocks.find((candidate: any) => candidate.id === block.id);
    assert(savedBlock?.content === "刷新后保存的正文", "next refresh must retain the canonical edit");
    assert(third.ui.activeId === lesson.id && third.ui.route === "media", "next refresh must retain reader position");
    assert(third.ui.mode === "preview" && third.ui.rightPanel === "status", "next refresh must retain mode and panel");
  } finally {
    await desktop.close();
    (globalThis as typeof globalThis & { document?: unknown }).document = previousDocument;
    (globalThis as typeof globalThis & { __TAURI__?: unknown }).__TAURI__ = previousTauri;
    globalThis.fetch = previousFetch;
  }
});

Deno.test("browser session records reject stale, corrupt, credential-shaped, missing, and inaccessible inputs", async () => {
  const directory = await Deno.makeTempDir({ prefix: "acw-browser-session-record-" });
  const projectId = "project-current";
  const session = {
    project_id: projectId,
    active_content_item_id: "lesson-1",
    mode: "preview",
    right_panel: "status",
    route: "media",
    left_collapsed: false,
    right_collapsed: true,
    tabs: [{ content_item_id: "lesson-1", mode: "preview", pinned: false, scroll_top: 12 }],
  };
  const store = new BrowserSessionStore(directory);
  try {
    await store.save(session, projectId);
    assert((await store.load(projectId))?.active_content_item_id === "lesson-1", "valid session should round-trip");

    await Deno.writeTextFile(store.path, "{not-json");
    assert(await store.load(projectId) === null, "corrupt sessions must degrade to no session");

    await Deno.writeTextFile(store.path, JSON.stringify({
      version: 1,
      project_root: directory,
      project_id: "project-old",
      session: { ...session, project_id: "project-old" },
    }));
    assert(await store.load(projectId) === null, "stale project ids must never restore");

    await Deno.writeTextFile(store.path, JSON.stringify({
      version: 1,
      project_root: "/another/project/root",
      project_id: projectId,
      session,
    }));
    assert(await store.load(projectId) === null, "stale project roots must never restore");

    let rejected = false;
    try {
      await store.save({ ...session, api_key: "must-not-persist" }, projectId);
    } catch (caught) {
      rejected = caught instanceof Error &&
        (caught as { error?: { code?: string } }).error?.code === "invalid_browser_session";
    }
    assert(rejected, "credential-shaped session fields must be rejected at the service boundary");
    assert(!await Deno.readTextFile(store.path).then((value) => value.includes("must-not-persist")), "rejected data must not reach disk");

    const missing = new BrowserSessionStore(`${directory}/missing-project`);
    assert(await missing.load(projectId) === null, "missing project roots must degrade to no session");
    let inaccessible = false;
    const notDirectory = `${directory}/not-a-directory`;
    await Deno.writeTextFile(notDirectory, "not a directory");
    try {
      await new BrowserSessionStore(notDirectory).save(session, projectId);
    } catch (caught) {
      inaccessible = caught instanceof Error &&
        (caught as { error?: { code?: string } }).error?.code === "browser_session_unavailable";
    }
    assert(inaccessible, "inaccessible project roots must return a safe structured failure");
  } finally {
    await Deno.remove(directory, { recursive: true }).catch(() => undefined);
  }
});

Deno.test("missing browser projects still render a usable launcher", async () => {
  const runtime = globalThis as typeof globalThis & { document?: unknown; __TAURI__?: unknown };
  const previousDocument = runtime.document;
  const previousTauri = runtime.__TAURI__;
  const previousFetch = globalThis.fetch;
  const directory = await Deno.makeTempDir({ prefix: "acw-browser-session-empty-" });
  const secrets = new MemorySecretStore();
  const desktop = new DesktopService(
    directory,
    { app_instance_id: `browser-empty-${crypto.randomUUID()}` },
    secrets,
    { credential_store: secrets },
  );
  try {
    await desktop.open();
    const store = await bootBrowserPage(desktop);
    assert(store.data.content_items.length === 0, "missing project must not invent canonical content");
    assert(store.ui.screen === "launcher", "missing project must leave the launcher usable");
  } finally {
    await desktop.close();
    runtime.document = previousDocument;
    runtime.__TAURI__ = previousTauri;
    globalThis.fetch = previousFetch;
    await Deno.remove(directory, { recursive: true }).catch(() => undefined);
  }
});
